[package]
name = "NextProxy"
version = "0.1.0"
edition = "2018"
license = "MIT"
description = "Basic Proxy Server written in Rust"

[[bin]]
name = "nextproxy"
path = "src/http_proxy.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = "0.12.1"
dialoguer = "0.11.0"
warp = "0.3.6"
